### ISSUE TITLE
Spinner location/size

### ISSUE THREAD

**Issue by fcarreno** [codekraft-studio/angular-page-loader#2]
@codekraft-studio  - this is a great directive to use during state transitions!
Any plans to update it to allow the spinner have specific size/location within the page?
It seems based on the current code, it ocupies the full html body.

Thanks!

**Comment by b4dnewz** [comment]
Hi, @fcarreno thanks for appreciating it!

Actually the directive will [auto-style](https://github.com/codekraft-studio/angular-page-loader/blob/master/src/angular-page-loader.directive.js#L33-L43) it self to occupy all the space of it's parent container.

In your specific case if you want to move around the loader, like for example inside a container you do like this:
```css
.my-box {
  position: relative;  /* <-- this is mandatory in this case */
  width: 500px;
  height: 500px;
  margin: 0 auto;
}
```
```html
<div class="my-box">
  <page-loader></page-loader>
</div>
```
If you want, you can be more specific in describing what you want to archive and I will help if needed.

Let me know if this helps with your issue.
